import AnimateText from "@/component/AnimateText";
import Layout from "@/component/Layout";
import TransactionEffect from "@/component/TransactionEffect";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef } from "react";
import avaG2 from "../../public/images/profile/avaG.jpeg";
import { useInView, useMotionValue, useSpring } from "framer-motion";
import Skills from "@/component/Skills";
import Experience from "@/component/Experience";
import Education from "@/component/Education";

const AnimateNumber = ({ value }) => {
  const ref = useRef(null);
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInView = useInView(ref, { once: true });
  useEffect(() => {
    if (isInView) {
      motionValue.set(value);
    }
  }, [isInView, motionValue, value]);
  useEffect(() => {
    springValue.on("change", (latest) => {
      // console.log(lastest);
      if (ref.current && latest.toFixed(0) <= value) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [springValue, value]);
  return <span ref={ref}></span>;
};

const About = () => {
  return (
    <>
      <Head>
        <title>About | Giang Personal Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/profile/avaG copy.svg" />
      </Head>
      <TransactionEffect />
      <div className="flex w-full flex-col items-center justify-center dark:text-light">
        <Layout className="pt-16">
          <AnimateText text={"Passion fuels purposel"} className="mb-16" />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex flex-col items-start justify-start">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75">
                Biography
              </h2>
              <p className="font-medium">
                Hi, I am Duong Truong Giang, a web developer and UI/UX designer
                with a passion for creating beautiful, functional, and
                user-centered digital experiences. With 2 years of experience in
                the field. I am always looking for new and innovative ways to
                bring my clients visions to life.
              </p>

              <p className="my-4 font-medium">
                - I believe that design is about more than just making things
                look pretty it is about solving problems and creating intuitive,
                enjoyable experiences for users.{" "}
              </p>

              <p className="font-medium">
                - Whether I am working on a website, mobile app, or other
                digital product, I bring my commitment to design excellence and
                user-centered thinking to every project I work on. I look
                forward to the opportunity to bring my skills and passion to
                your next project.
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border border-solid border-dark bg-light p-8 dark:bg-dark dark:border-light">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light" />
              <Image
                src={avaG2}
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
                alt="about"
                className="w-full h-auto object-cover rounded-2xl"
              />
            </div>
            <div className="col-span-2 flex flex-col items-end justify-between">
              <div className="flex flex-col items-end justify-between">
                <span className="inline-block text-7xl font-bold">
                  <AnimateNumber value={50} />+
                </span>
                <h2 className="font-medium text-xl capitalize text-dark/75 dark:text-light">
                  Satisfied clients
                </h2>
              </div>
              <div className="flex flex-col items-end justify-between">
                <span className="inline-block text-7xl font-bold">
                  <AnimateNumber value={40} />+
                </span>
                <h2 className="font-medium text-xl capitalize text-dark/75 dark:text-light">
                  Project completed
                </h2>
              </div>
              <div className="flex flex-col items-end justify-between">
                <span className="inline-block text-7xl font-bold">
                  <AnimateNumber value={2} />+
                </span>
                <h2 className="font-medium text-xl capitalize text-dark/75 dark:text-light">
                  Year of Experience
                </h2>
              </div>
            </div>
          </div>
          <Skills />
          <Experience />
          <Education />
        </Layout>
      </div>
    </>
  );
};

export default About;
