import AnimateText from "@/component/AnimateText";
import { GithubIcon } from "@/component/Icons";
import Layout from "@/component/Layout";
import TransactionEffect from "@/component/TransactionEffect";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import project from "../../public/images/projects/crypto-screener-cover-image.jpg";
import project1 from "../../public/images/projects/image1.png";
import project2 from "../../public/images/projects/image2.png";
import project3 from "../../public/images/projects/image3.png";
import project4 from "../../public/images/projects/image4.png";

import { motion } from "framer-motion";

const FramerImage = motion(Image);
const Feature = ({ type, title, img, sumary, link, github }) => {
  return (
    <article
      className="w-full flex items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-12 relative rounded-br-2xl dark:border-light dark:bg-dark
    lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4
    "
    >
      <div className="absolute top-0 rounded-br-3xl -right-3 -z-10 w-[100%] h-[103%] rounded-[2.5rem] bg-dark dark:bg-light xs:-right-2 sm:h-[102%] xs:w-full xs:rounded-[1.5rem]" />
      <Link href={""} className="w-1/2 cursor-pointer rounded-lg lg:w-full">
        <FramerImage
          src={img}
          alt=""
          priority
          sizes="(max-width: 768px) 100vw,
        (max-width: 1200px) 50vw,
        33vw"
          className="w-full h-auto rounded-lg"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.4 }}
        />
      </Link>
      <div className="w-1/2 flex flex-col items-start justify-between pl-6 lg:w-full lg:pl-0 lg:pt-6">
        <span className="text-primary font-bold text-xl xs:text-base">
          {type}
        </span>
        <Link
          href={link}
          target="_blank"
          className="underline-offset-2 hover:underline"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold dark:text-light sm:text-sm">
            {title}
          </h2>
        </Link>
        <p className="text-dark font-medium my-2 dark:text-light">{sumary}</p>
        <div className="flex items-center mt-2">
          <Link href={github} target="_blank">
            <GithubIcon className="w-10 dark:bg-light p-2 rounded-full" />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 rounded-lg bg-dark text-light p-2 px-6 text-lg font-semibold dark:text-light sm:px-4 sm:text-base"
          >
            Visit Website
          </Link>
        </div>
      </div>
    </article>
  );
};

const FeatureProject = ({ type, title, img, github, link }) => {
  return (
    <article className="w-full flex flex-col items-center justify-between rounded-3xl border border-solid border-dark bg-light shadow-2xl p-6 relative rounded-br-2xl dark:border-light dark:bg-dark xs:p-4">
      <div className="absolute top-0 rounded-br-3xl -right-3 -z-10 w-[100%] h-[103%] rounded-[2.5rem] bg-dark dark:bg-light md:-right-2 md:w-[101%] xs:h-[102%] xs:rounded-[1.5rem]" />
      <Link href={""} className="w-full cursor-pointer rounded-lg">
        <FramerImage
          src={img}
          alt=""
          className="w-full h-auto rounded-lg"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.4 }}
        />
      </Link>
      <div className="w-full flex flex-col items-start justify-between mt-4">
        <span className="text-primary font-bold text-xl dark:text-light lg:text-lg md:text-base">
          {type}
        </span>
        <Link
          href={link}
          target="_blank"
          className="underline-offset-2 hover:underline"
        >
          <h2 className="my-2 w-full text-left text-3xl font-bold dark:text-light lg:text-2xl">
            {title}
          </h2>
        </Link>
        <div className="flex items-center mt-2 justify-between w-full">
          <Link href={github} target="_blank">
            <GithubIcon className="w-8 dark:bg-light p-2 rounded-full md:w-6" />
          </Link>
          <Link
            href={link}
            target="_blank"
            className="ml-4 text-lg font-semibold underline dark:text-light md:text-base"
          >
            Visit Website
          </Link>
        </div>
      </div>
    </article>
  );
};
const Project = () => {
  return (
    <>
      <Head>
        <title>Project | Giang Personal Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/profile/avaG copy.svg" />
      </Head>
      <TransactionEffect />
      <div className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimateText
            text={"My projects"}
            className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:text-4xl"
          />
          <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
            <div className="col-span-12">
              <Feature
                type="Imagination Trumps Knowledge!"
                title="Crypto Screener Application"
                img={project}
                sumary="A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts.
                It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your
                local currency."
                link="link"
                github="github"
              />
            </div>
            <div className="col-span-6 sm:col-span-12">
              <FeatureProject
                type="Imagination Trumps Knowledge!"
                title="Crypto Screener Application"
                img={project1}
                link="link"
                github="github"
              />
            </div>
            <div className="col-span-6 sm:col-span-12">
              <FeatureProject
                type="Imagination Trumps Knowledge!"
                title="Crypto Screener Application"
                img={project2}
                link="link"
                github="github"
              />
            </div>
            <div className="col-span-12 ">
              <Feature
                type="Imagination Trumps Knowledge!"
                title="Crypto Screener Application"
                img={project}
                sumary="A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts.
                It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your
                local currency."
                link="link"
                github="github"
              />
            </div>
            <div className="col-span-6 sm:col-span-12">
              <FeatureProject
                type="Imagination Trumps Knowledge!"
                title="Crypto Screener Application"
                img={project3}
                link="link"
                github="github"
              />
            </div>
            <div className="col-span-6 sm:col-span-12">
              <FeatureProject
                type="Imagination Trumps Knowledge!"
                title="Crypto Screener Application"
                img={project4}
                link="link"
                github="github"
              />
            </div>
          </div>
        </Layout>
      </div>
    </>
  );
};

export default Project;
